/* eslint-disable */
export type TokenResult = string & { var: string }

export declare const aspectRatios_square: TokenResult
export declare const aspectRatios_landscape: TokenResult
export declare const aspectRatios_portrait: TokenResult
export declare const aspectRatios_wide: TokenResult
export declare const aspectRatios_ultrawide: TokenResult
export declare const aspectRatios_golden: TokenResult
export declare const borders_none: TokenResult
export declare const easings_default: TokenResult
export declare const easings_linear: TokenResult
export declare const easings_in: TokenResult
export declare const easings_out: TokenResult
export declare const easings_innout: TokenResult
export declare const durations_fastest: TokenResult
export declare const durations_faster: TokenResult
export declare const durations_fast: TokenResult
export declare const durations_normal: TokenResult
export declare const durations_slow: TokenResult
export declare const durations_slower: TokenResult
export declare const durations_slowest: TokenResult
export declare const radii_xs: TokenResult
export declare const radii_sm: TokenResult
export declare const radii_md: TokenResult
export declare const radii_lg: TokenResult
export declare const radii_xl: TokenResult
export declare const radii_2xl: TokenResult
export declare const radii_3xl: TokenResult
export declare const radii_4xl: TokenResult
export declare const radii_full: TokenResult
export declare const fontWeights_thin: TokenResult
export declare const fontWeights_extralight: TokenResult
export declare const fontWeights_light: TokenResult
export declare const fontWeights_normal: TokenResult
export declare const fontWeights_medium: TokenResult
export declare const fontWeights_semibold: TokenResult
export declare const fontWeights_bold: TokenResult
export declare const fontWeights_extrabold: TokenResult
export declare const fontWeights_black: TokenResult
export declare const lineHeights_none: TokenResult
export declare const lineHeights_tight: TokenResult
export declare const lineHeights_snug: TokenResult
export declare const lineHeights_normal: TokenResult
export declare const lineHeights_relaxed: TokenResult
export declare const lineHeights_loose: TokenResult
export declare const fonts_sans: TokenResult
export declare const fonts_serif: TokenResult
export declare const fonts_mono: TokenResult
export declare const letterSpacings_tighter: TokenResult
export declare const letterSpacings_tight: TokenResult
export declare const letterSpacings_normal: TokenResult
export declare const letterSpacings_wide: TokenResult
export declare const letterSpacings_wider: TokenResult
export declare const letterSpacings_widest: TokenResult
export declare const fontSizes_2xs: TokenResult
export declare const fontSizes_xs: TokenResult
export declare const fontSizes_sm: TokenResult
export declare const fontSizes_md: TokenResult
export declare const fontSizes_lg: TokenResult
export declare const fontSizes_xl: TokenResult
export declare const fontSizes_2xl: TokenResult
export declare const fontSizes_3xl: TokenResult
export declare const fontSizes_4xl: TokenResult
export declare const fontSizes_5xl: TokenResult
export declare const fontSizes_6xl: TokenResult
export declare const fontSizes_7xl: TokenResult
export declare const fontSizes_8xl: TokenResult
export declare const fontSizes_9xl: TokenResult
export declare const shadows_xs: TokenResult
export declare const shadows_sm: TokenResult
export declare const shadows_md: TokenResult
export declare const shadows_lg: TokenResult
export declare const shadows_xl: TokenResult
export declare const shadows_2xl: TokenResult
export declare const shadows_inner: TokenResult
export declare const blurs_sm: TokenResult
export declare const blurs_base: TokenResult
export declare const blurs_md: TokenResult
export declare const blurs_lg: TokenResult
export declare const blurs_xl: TokenResult
export declare const blurs_2xl: TokenResult
export declare const blurs_3xl: TokenResult
export declare const spacing_0: TokenResult
export declare const spacing_1: TokenResult
export declare const spacing_2: TokenResult
export declare const spacing_3: TokenResult
export declare const spacing_4: TokenResult
export declare const spacing_5: TokenResult
export declare const spacing_6: TokenResult
export declare const spacing_7: TokenResult
export declare const spacing_8: TokenResult
export declare const spacing_9: TokenResult
export declare const spacing_10: TokenResult
export declare const spacing_11: TokenResult
export declare const spacing_12: TokenResult
export declare const spacing_14: TokenResult
export declare const spacing_16: TokenResult
export declare const spacing_20: TokenResult
export declare const spacing_24: TokenResult
export declare const spacing_28: TokenResult
export declare const spacing_32: TokenResult
export declare const spacing_36: TokenResult
export declare const spacing_40: TokenResult
export declare const spacing_44: TokenResult
export declare const spacing_48: TokenResult
export declare const spacing_52: TokenResult
export declare const spacing_56: TokenResult
export declare const spacing_60: TokenResult
export declare const spacing_64: TokenResult
export declare const spacing_72: TokenResult
export declare const spacing_80: TokenResult
export declare const spacing_96: TokenResult
export declare const spacing_0_5: TokenResult
export declare const spacing_1_5: TokenResult
export declare const spacing_2_5: TokenResult
export declare const spacing_3_5: TokenResult
export declare const sizes_0: TokenResult
export declare const sizes_1: TokenResult
export declare const sizes_2: TokenResult
export declare const sizes_3: TokenResult
export declare const sizes_4: TokenResult
export declare const sizes_5: TokenResult
export declare const sizes_6: TokenResult
export declare const sizes_7: TokenResult
export declare const sizes_8: TokenResult
export declare const sizes_9: TokenResult
export declare const sizes_10: TokenResult
export declare const sizes_11: TokenResult
export declare const sizes_12: TokenResult
export declare const sizes_14: TokenResult
export declare const sizes_16: TokenResult
export declare const sizes_20: TokenResult
export declare const sizes_24: TokenResult
export declare const sizes_28: TokenResult
export declare const sizes_32: TokenResult
export declare const sizes_36: TokenResult
export declare const sizes_40: TokenResult
export declare const sizes_44: TokenResult
export declare const sizes_48: TokenResult
export declare const sizes_52: TokenResult
export declare const sizes_56: TokenResult
export declare const sizes_60: TokenResult
export declare const sizes_64: TokenResult
export declare const sizes_72: TokenResult
export declare const sizes_80: TokenResult
export declare const sizes_96: TokenResult
export declare const sizes_0_5: TokenResult
export declare const sizes_1_5: TokenResult
export declare const sizes_2_5: TokenResult
export declare const sizes_3_5: TokenResult
export declare const sizes_xs: TokenResult
export declare const sizes_sm: TokenResult
export declare const sizes_md: TokenResult
export declare const sizes_lg: TokenResult
export declare const sizes_xl: TokenResult
export declare const sizes_2xl: TokenResult
export declare const sizes_3xl: TokenResult
export declare const sizes_4xl: TokenResult
export declare const sizes_5xl: TokenResult
export declare const sizes_6xl: TokenResult
export declare const sizes_7xl: TokenResult
export declare const sizes_8xl: TokenResult
export declare const sizes_prose: TokenResult
export declare const sizes_full: TokenResult
export declare const sizes_min: TokenResult
export declare const sizes_max: TokenResult
export declare const sizes_fit: TokenResult
export declare const sizes_breakpointnsm: TokenResult
export declare const sizes_breakpointnmd: TokenResult
export declare const sizes_breakpointnlg: TokenResult
export declare const sizes_breakpointnxl: TokenResult
export declare const sizes_breakpointn2xl: TokenResult
export declare const animations_spin: TokenResult
export declare const animations_ping: TokenResult
export declare const animations_pulse: TokenResult
export declare const animations_bounce: TokenResult
export declare const colors_current: TokenResult
export declare const colors_black: TokenResult
export declare const colors_white: TokenResult
export declare const colors_transparent: TokenResult
export declare const colors_rose_50: TokenResult
export declare const colors_rose_100: TokenResult
export declare const colors_rose_200: TokenResult
export declare const colors_rose_300: TokenResult
export declare const colors_rose_400: TokenResult
export declare const colors_rose_500: TokenResult
export declare const colors_rose_600: TokenResult
export declare const colors_rose_700: TokenResult
export declare const colors_rose_800: TokenResult
export declare const colors_rose_900: TokenResult
export declare const colors_rose_950: TokenResult
export declare const colors_pink_50: TokenResult
export declare const colors_pink_100: TokenResult
export declare const colors_pink_200: TokenResult
export declare const colors_pink_300: TokenResult
export declare const colors_pink_400: TokenResult
export declare const colors_pink_500: TokenResult
export declare const colors_pink_600: TokenResult
export declare const colors_pink_700: TokenResult
export declare const colors_pink_800: TokenResult
export declare const colors_pink_900: TokenResult
export declare const colors_pink_950: TokenResult
export declare const colors_fuchsia_50: TokenResult
export declare const colors_fuchsia_100: TokenResult
export declare const colors_fuchsia_200: TokenResult
export declare const colors_fuchsia_300: TokenResult
export declare const colors_fuchsia_400: TokenResult
export declare const colors_fuchsia_500: TokenResult
export declare const colors_fuchsia_600: TokenResult
export declare const colors_fuchsia_700: TokenResult
export declare const colors_fuchsia_800: TokenResult
export declare const colors_fuchsia_900: TokenResult
export declare const colors_fuchsia_950: TokenResult
export declare const colors_purple_50: TokenResult
export declare const colors_purple_100: TokenResult
export declare const colors_purple_200: TokenResult
export declare const colors_purple_300: TokenResult
export declare const colors_purple_400: TokenResult
export declare const colors_purple_500: TokenResult
export declare const colors_purple_600: TokenResult
export declare const colors_purple_700: TokenResult
export declare const colors_purple_800: TokenResult
export declare const colors_purple_900: TokenResult
export declare const colors_purple_950: TokenResult
export declare const colors_violet_50: TokenResult
export declare const colors_violet_100: TokenResult
export declare const colors_violet_200: TokenResult
export declare const colors_violet_300: TokenResult
export declare const colors_violet_400: TokenResult
export declare const colors_violet_500: TokenResult
export declare const colors_violet_600: TokenResult
export declare const colors_violet_700: TokenResult
export declare const colors_violet_800: TokenResult
export declare const colors_violet_900: TokenResult
export declare const colors_violet_950: TokenResult
export declare const colors_indigo_50: TokenResult
export declare const colors_indigo_100: TokenResult
export declare const colors_indigo_200: TokenResult
export declare const colors_indigo_300: TokenResult
export declare const colors_indigo_400: TokenResult
export declare const colors_indigo_500: TokenResult
export declare const colors_indigo_600: TokenResult
export declare const colors_indigo_700: TokenResult
export declare const colors_indigo_800: TokenResult
export declare const colors_indigo_900: TokenResult
export declare const colors_indigo_950: TokenResult
export declare const colors_blue_50: TokenResult
export declare const colors_blue_100: TokenResult
export declare const colors_blue_200: TokenResult
export declare const colors_blue_300: TokenResult
export declare const colors_blue_400: TokenResult
export declare const colors_blue_500: TokenResult
export declare const colors_blue_600: TokenResult
export declare const colors_blue_700: TokenResult
export declare const colors_blue_800: TokenResult
export declare const colors_blue_900: TokenResult
export declare const colors_blue_950: TokenResult
export declare const colors_sky_50: TokenResult
export declare const colors_sky_100: TokenResult
export declare const colors_sky_200: TokenResult
export declare const colors_sky_300: TokenResult
export declare const colors_sky_400: TokenResult
export declare const colors_sky_500: TokenResult
export declare const colors_sky_600: TokenResult
export declare const colors_sky_700: TokenResult
export declare const colors_sky_800: TokenResult
export declare const colors_sky_900: TokenResult
export declare const colors_sky_950: TokenResult
export declare const colors_cyan_50: TokenResult
export declare const colors_cyan_100: TokenResult
export declare const colors_cyan_200: TokenResult
export declare const colors_cyan_300: TokenResult
export declare const colors_cyan_400: TokenResult
export declare const colors_cyan_500: TokenResult
export declare const colors_cyan_600: TokenResult
export declare const colors_cyan_700: TokenResult
export declare const colors_cyan_800: TokenResult
export declare const colors_cyan_900: TokenResult
export declare const colors_cyan_950: TokenResult
export declare const colors_teal_50: TokenResult
export declare const colors_teal_100: TokenResult
export declare const colors_teal_200: TokenResult
export declare const colors_teal_300: TokenResult
export declare const colors_teal_400: TokenResult
export declare const colors_teal_500: TokenResult
export declare const colors_teal_600: TokenResult
export declare const colors_teal_700: TokenResult
export declare const colors_teal_800: TokenResult
export declare const colors_teal_900: TokenResult
export declare const colors_teal_950: TokenResult
export declare const colors_emerald_50: TokenResult
export declare const colors_emerald_100: TokenResult
export declare const colors_emerald_200: TokenResult
export declare const colors_emerald_300: TokenResult
export declare const colors_emerald_400: TokenResult
export declare const colors_emerald_500: TokenResult
export declare const colors_emerald_600: TokenResult
export declare const colors_emerald_700: TokenResult
export declare const colors_emerald_800: TokenResult
export declare const colors_emerald_900: TokenResult
export declare const colors_emerald_950: TokenResult
export declare const colors_green_50: TokenResult
export declare const colors_green_100: TokenResult
export declare const colors_green_200: TokenResult
export declare const colors_green_300: TokenResult
export declare const colors_green_400: TokenResult
export declare const colors_green_500: TokenResult
export declare const colors_green_600: TokenResult
export declare const colors_green_700: TokenResult
export declare const colors_green_800: TokenResult
export declare const colors_green_900: TokenResult
export declare const colors_green_950: TokenResult
export declare const colors_lime_50: TokenResult
export declare const colors_lime_100: TokenResult
export declare const colors_lime_200: TokenResult
export declare const colors_lime_300: TokenResult
export declare const colors_lime_400: TokenResult
export declare const colors_lime_500: TokenResult
export declare const colors_lime_600: TokenResult
export declare const colors_lime_700: TokenResult
export declare const colors_lime_800: TokenResult
export declare const colors_lime_900: TokenResult
export declare const colors_lime_950: TokenResult
export declare const colors_yellow_50: TokenResult
export declare const colors_yellow_100: TokenResult
export declare const colors_yellow_200: TokenResult
export declare const colors_yellow_300: TokenResult
export declare const colors_yellow_400: TokenResult
export declare const colors_yellow_500: TokenResult
export declare const colors_yellow_600: TokenResult
export declare const colors_yellow_700: TokenResult
export declare const colors_yellow_800: TokenResult
export declare const colors_yellow_900: TokenResult
export declare const colors_yellow_950: TokenResult
export declare const colors_amber_50: TokenResult
export declare const colors_amber_100: TokenResult
export declare const colors_amber_200: TokenResult
export declare const colors_amber_300: TokenResult
export declare const colors_amber_400: TokenResult
export declare const colors_amber_500: TokenResult
export declare const colors_amber_600: TokenResult
export declare const colors_amber_700: TokenResult
export declare const colors_amber_800: TokenResult
export declare const colors_amber_900: TokenResult
export declare const colors_amber_950: TokenResult
export declare const colors_orange_50: TokenResult
export declare const colors_orange_100: TokenResult
export declare const colors_orange_200: TokenResult
export declare const colors_orange_300: TokenResult
export declare const colors_orange_400: TokenResult
export declare const colors_orange_500: TokenResult
export declare const colors_orange_600: TokenResult
export declare const colors_orange_700: TokenResult
export declare const colors_orange_800: TokenResult
export declare const colors_orange_900: TokenResult
export declare const colors_orange_950: TokenResult
export declare const colors_red_50: TokenResult
export declare const colors_red_100: TokenResult
export declare const colors_red_200: TokenResult
export declare const colors_red_300: TokenResult
export declare const colors_red_400: TokenResult
export declare const colors_red_500: TokenResult
export declare const colors_red_600: TokenResult
export declare const colors_red_700: TokenResult
export declare const colors_red_800: TokenResult
export declare const colors_red_900: TokenResult
export declare const colors_red_950: TokenResult
export declare const colors_stone_50: TokenResult
export declare const colors_stone_100: TokenResult
export declare const colors_stone_200: TokenResult
export declare const colors_stone_300: TokenResult
export declare const colors_stone_400: TokenResult
export declare const colors_stone_500: TokenResult
export declare const colors_stone_600: TokenResult
export declare const colors_stone_700: TokenResult
export declare const colors_stone_800: TokenResult
export declare const colors_stone_900: TokenResult
export declare const colors_stone_950: TokenResult
export declare const colors_zinc_50: TokenResult
export declare const colors_zinc_100: TokenResult
export declare const colors_zinc_200: TokenResult
export declare const colors_zinc_300: TokenResult
export declare const colors_zinc_400: TokenResult
export declare const colors_zinc_500: TokenResult
export declare const colors_zinc_600: TokenResult
export declare const colors_zinc_700: TokenResult
export declare const colors_zinc_800: TokenResult
export declare const colors_zinc_900: TokenResult
export declare const colors_zinc_950: TokenResult
export declare const colors_gray_50: TokenResult
export declare const colors_gray_100: TokenResult
export declare const colors_gray_200: TokenResult
export declare const colors_gray_300: TokenResult
export declare const colors_gray_400: TokenResult
export declare const colors_gray_500: TokenResult
export declare const colors_gray_600: TokenResult
export declare const colors_gray_700: TokenResult
export declare const colors_gray_800: TokenResult
export declare const colors_gray_900: TokenResult
export declare const colors_gray_950: TokenResult
export declare const colors_slate_50: TokenResult
export declare const colors_slate_100: TokenResult
export declare const colors_slate_200: TokenResult
export declare const colors_slate_300: TokenResult
export declare const colors_slate_400: TokenResult
export declare const colors_slate_500: TokenResult
export declare const colors_slate_600: TokenResult
export declare const colors_slate_700: TokenResult
export declare const colors_slate_800: TokenResult
export declare const colors_slate_900: TokenResult
export declare const colors_slate_950: TokenResult
export declare const colors_neutral_50: TokenResult
export declare const colors_neutral_100: TokenResult
export declare const colors_neutral_200: TokenResult
export declare const colors_neutral_300: TokenResult
export declare const colors_neutral_400: TokenResult
export declare const colors_neutral_500: TokenResult
export declare const colors_neutral_600: TokenResult
export declare const colors_neutral_700: TokenResult
export declare const colors_neutral_800: TokenResult
export declare const colors_neutral_900: TokenResult
export declare const colors_neutral_950: TokenResult
export declare const assets_check: TokenResult
export declare const breakpoints_sm: TokenResult
export declare const breakpoints_md: TokenResult
export declare const breakpoints_lg: TokenResult
export declare const breakpoints_xl: TokenResult
export declare const breakpoints_2xl: TokenResult
export declare const shadows_inset: TokenResult
export declare const colors_text: TokenResult
export declare const colors_bg: TokenResult
export declare const colors_card: TokenResult
export declare const colors_border: TokenResult
export declare const colors_accent: TokenResult
export declare const spacing_n1: TokenResult
export declare const spacing_n2: TokenResult
export declare const spacing_n3: TokenResult
export declare const spacing_n4: TokenResult
export declare const spacing_n5: TokenResult
export declare const spacing_n6: TokenResult
export declare const spacing_n7: TokenResult
export declare const spacing_n8: TokenResult
export declare const spacing_n9: TokenResult
export declare const spacing_n10: TokenResult
export declare const spacing_n11: TokenResult
export declare const spacing_n12: TokenResult
export declare const spacing_n14: TokenResult
export declare const spacing_n16: TokenResult
export declare const spacing_n20: TokenResult
export declare const spacing_n24: TokenResult
export declare const spacing_n28: TokenResult
export declare const spacing_n32: TokenResult
export declare const spacing_n36: TokenResult
export declare const spacing_n40: TokenResult
export declare const spacing_n44: TokenResult
export declare const spacing_n48: TokenResult
export declare const spacing_n52: TokenResult
export declare const spacing_n56: TokenResult
export declare const spacing_n60: TokenResult
export declare const spacing_n64: TokenResult
export declare const spacing_n72: TokenResult
export declare const spacing_n80: TokenResult
export declare const spacing_n96: TokenResult
export declare const spacing_n0_5: TokenResult
export declare const spacing_n1_5: TokenResult
export declare const spacing_n2_5: TokenResult
export declare const spacing_n3_5: TokenResult
export declare const colors_colorPalette: TokenResult
export declare const colors_colorPalette_50: TokenResult
export declare const colors_colorPalette_100: TokenResult
export declare const colors_colorPalette_200: TokenResult
export declare const colors_colorPalette_300: TokenResult
export declare const colors_colorPalette_400: TokenResult
export declare const colors_colorPalette_500: TokenResult
export declare const colors_colorPalette_600: TokenResult
export declare const colors_colorPalette_700: TokenResult
export declare const colors_colorPalette_800: TokenResult
export declare const colors_colorPalette_900: TokenResult
export declare const colors_colorPalette_950: TokenResult